### ISSUE TITLE
Module parse failed: Identifier 'callServer' has already been declared

### ISSUE THREAD

**Issue by amosbastian** [pingdotgg/zact#28]
Getting this error when trying to use it in an Nx monorepo, but only when putting it in a separate lib:

```
error - ../../libs/feature/src/lib/action.ts
Module parse failed: Identifier 'callServer' has already been declared (8:9)
| }
|
> import { callServer } from "next/dist/client/app-call-server";
| function __build_action__(action, args) {
|     return callServer(action.$$id, args);

Import trace for requested module:
../../libs/feature/src/lib/action.ts
../../libs/feature/src/lib/t3test.tsx
```

I'm using the same component as the example app in this repository

```ts
// This doesn't work:
import { T3TestComponent } from '@zact-nx/feature';

// This works:
// import { T3TestComponent } from './t3test';

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <T3TestComponent />
    </main>
  );
}
```

If I put the action and client component in the app directory and import that, it works fine. If I put it in a different lib and import it from there, it does not work.

I also noticed that the example app has `transpilePackages: ['zact']` in its `next.config.js`, but if I set that, then I get this error:

```
../../libs/feature/src/lib/t3test.tsx
ReactServerComponentsError:

The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.

   ╭─[/Users/amosbastian/Development/zact-nx/node_modules/zact/client.mjs:1:1]
 1 │ // client.ts
 2 │ import { useMemo, useRef, useState } from "react";
 3 │ "use client";
   · ─────────────
 4 │ function useZact(action) {
 5 │   const doAction = useRef(action);
 6 │   const [data, setData] = useState(null);
   ╰────

The error was caused by importing 'zact/client.mjs' in '../../libs/feature/src/lib/t3test.tsx'.

Import path:
  ../../libs/feature/src/lib/t3test.tsx
```
  
You can test it out yourself by cloning this repository: https://github.com/amosbastian/zact-nx and running

```
npm i
npx nx serve web
```

and visiting http://localhost:4200

**Comment by chungweileong94** [comment]
Yeah, a simple example repo would be good. I can't spot anything at all.

**Comment by amosbastian** [comment]
I have a reproduction repository, will share it once GitHub actually lets me push it 😭

**Comment by amosbastian** [comment]
I've updated my post with more information and a link to the repository @chungweileong94

**Comment by chungweileong94** [comment]
I have a feeling that the NX is yet to understand `use server` in another workspace.

**Comment by amosbastian** [comment]
I'm closing it here as I've confirmed it has nothing to do with zact, but just with Nx
